### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Aerodlyn** [c-asta/dvp-u3-constellations#1]
https://github.com/c-asta/dvp-u3-constellations/blob/9b95a849101702278b8099681baaeb520dc0cc67/Documents/constellation_christopher_asta.py#L73-L77

This is the only issue I see with your code. You should be calling `scatter` on the `axes` object that is returned by `add_subplot` like you did below:

https://github.com/c-asta/dvp-u3-constellations/blob/9b95a849101702278b8099681baaeb520dc0cc67/Documents/constellation_christopher_asta.py#L108-L115

Otherwise, good job!

**Comment by c-asta** [comment]
Awesome, thanks for the review!
